# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77abb6bbfee90b70cc037772bc3cb00a59158ae66bf9125357a6e9e487182c1399a760fd30cb3c53d87106b22048ff6e390352dc1c7dbdc6d5ddc0418fe879da

test:
  secret_key_base: dea1c9593f7f3c7c791bef05a24449338cfa841910448fdb704493f77e1731aea6bf363d4c3c1929a994fab1a059d917a4c1fa4bf6e62bfb54eb81322d0c2281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
